services:
  collabora-online-app:
    image: tiredofit/collabora-online
    container_name: collabora-online-app
    hostname: code.lebardaun.com
    cap_add:
      - MKNOD
      - NET_ADMIN
    privileged: true

    volumes:
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=collabora-online-app

      - ADMIN_USER=admin
      - ADMIN_PASS=cT3r53r4hl4h?!?/

      - ALLOWED_HOSTS=nextcloud.lebardaun.com,code.lebardaun.com

      - ENABLE_TLS=FALSE
      - ENABLE_TLS_REVERSE_PROXY=TRUE

      - INTERFACE=notebookbar
      - LOG_TYPE=FILE
    networks:
      - bridge
    restart: always

networks:
  bridge:
    external: true
